version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
      args:
        - NGINXUSER=${NGINXUSER:-www-data}
        - NGINXGROUP=${NGINXGROUP:-www-data}
    container_name: kvc1_nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - kvcmysql
    networks:
      - laravel

  kvcmysql:
    image: mysql:5.7.29
    platform: linux/x86_64  # No arm64 version is available
    container_name: kvcmysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: kvcmysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    container_name: kvc1_php
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: kvc1_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: .docker/composer.dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    container_name: kvc1_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${PHPUSER:-www-data}
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: kvc1_npm
    volumes:
      - ./:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001  # todo why 3001?
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    container_name: kvc1_artisan
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - kvcmysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

volumes:
  db: # anonymous volume for the database
